Minor optimizations
gnembon/carpetmod112 pull request #116
Opened 2020-07-02 20:27 UTC by gsquaredxc

Cleaning up some code to help slightly improve performance, is draft for now. Mainly was to help readability but some things can help make the code faster.

2020-07-02 21:23 UTC, Earthcomputer requested changes
The rest of the PR is IMO okay as just a general cleanup PR, none of this is optimizations though.

2020-07-02 21:23 UTC, Earthcomputer commented on patches/net/minecraft/server/MinecraftServer.java.patch
> +-import java.util.function.Supplier;
Do not add patches to remove warnings from vanilla code. None of these changes to this class are actual optimizations.

2020-07-03 20:30 UTC, gsquaredxc commented on patches/net/minecraft/server/MinecraftServer.java.patch
> +-import java.util.function.Supplier;
Just to double check, this is just the import right? I also removed some unused variables that were just there for no reason.

2020-07-03 21:46 UTC, Earthcomputer commented on patches/net/minecraft/server/MinecraftServer.java.patch
> +-import java.util.function.Supplier;
It is almost everything you changed in this class. None of them are optimizations. The variables are generated by the decompiler and will be removed by the JIT if not the compiler itself. The vast majority of this PR is mostly just style fixes and not effective optimizations like you are aiming. I am fine with style fixes (although it's ultimately up to Xcom), however don't fix the style of the decompiler.

2020-07-04 12:02 UTC, Earthcomputer requested changes
Changes to vanilla code need carpet rules. Please limit the scope of this PR to cleaning up carpet code only.

2020-07-04 12:35 UTC, X-com requested changes
Agree with earth here. That's just some mess fern flower spits out. I doubt it influences runtime operation by more then few nanoseconds, but on the other hand it generates another patch and possibly causes future problems when binary's cause issues again. Just leave vanilla fields totally alone.

2022-06-03 17:46 UTC, closed without merging