Falling blocks and better commands added
gnembon/carpetmod112 pull request #151
Opened 2021-05-23 21:34 UTC by kweber1

2021-05-23 21:37 UTC, Earthcomputer requested changes

2021-05-23 21:37 UTC, Earthcomputer commented on carpetmodSrc/carpet/commands/CommandLazyChunkBehavior.java
> +            throw new WrongUsageException(getUsage(sender), new Object[0]);
Varargs means you don't need this parameter
```suggestion
            throw new WrongUsageException(getUsage(sender));
```

2021-05-23 21:37 UTC, Earthcomputer commented on carpetmodSrc/carpet/commands/CommandLazyChunkBehavior.java
> +            throw new WrongUsageException(getUsage(sender), new Object[0]);
Same here

2021-05-23 21:37 UTC, Earthcomputer commented on carpetmodSrc/carpet/commands/CommandLazyChunkBehavior.java
> +        if(args.length<1 || args.length>3){
Can you add some spaces before and after the inequality signs?

2021-05-24 02:38 UTC, kerbaras requested changes

2021-05-24 02:38 UTC, kerbaras commented on patches/net/minecraft/block/BlockFalling.java.patch
> ++                    }
i don't understand this change in the patch, did identation changed? lets try keep the patch modifications as minimal as possible

2021-05-24 03:06 UTC, kerbaras approved these changes
Fine for me, lets wait for earth to approve his review

2021-05-24 11:21 UTC, Earthcomputer approved these changes

2021-05-24 11:21 UTC, merged