added explosion logger
gnembon/carpetmod112 pull request #163
Opened 2021-10-10 05:47 UTC by Sylk0s

I ported the explosion logger from fabric-carpet into 1.12 (which is way better to use than the tnt logger). I also implemented Intricate's "compact" version from her carpet extension. Plan to use this to develop tnt tech in 1.12. I'm also not really sure what all the wacky stuff in the WorldServer file is...

2021-10-16 14:35 UTC, skyrising approved these changes

2021-10-17 20:01 UTC, Earthcomputer requested changes

2021-10-17 20:01 UTC, Earthcomputer commented on carpetmodSrc/carpet/logging/logHelpers/ExplosionLogHelper.java
> +        if(!(lastGametime==gametime)) {
```suggestion
        if(lastGametime != gametime) {
```

2021-10-17 20:01 UTC, Earthcomputer commented on patches/net/minecraft/world/Explosion.java.patch
> ++        logHelper.onExplosionDone(this.field_77287_j.func_72820_D());
Won't this crash if `LoggerRegistry.__explosions` was false in the constructor?

2021-10-17 22:44 UTC, sylk0s commented
I added the one syntax change and fixed a few small bugs. Added if statements so it wouldn't break like Earth mentioned and also fixed that same bug in the WorldServer class. I also fixed a bug where it didn't work if optimized tnt was on.

2021-10-30 14:46 UTC, kerbaras approved these changes

2021-10-30 14:47 UTC, kerbaras commented
@Earthcomputer do you think now its safe for merge? comments have been fixed :)

2021-10-30 15:51 UTC, Sylk0s commented
ty kerb <3

2021-10-30 17:41 UTC, Earthcomputer commented
Yes

2021-10-30 17:41 UTC, Earthcomputer approved these changes

2021-10-30 17:41 UTC, merged