Add integration with the new Redstone Multimeter mod
gnembon/carpetmod112 pull request #169
Opened 2022-02-01 20:43 UTC by SpaceWalkerRS

This PR adds integration with the [new Redstone Multimeter mod](https://github.com/SpaceWalkerRS/redstone-multimeter-fabric). 
- Integration with the original "legacy" Redstone Multimeter mod has not been removed, but instead moved under the `redstoneMultimeterLegacy` carpet rule, whereas the `redstoneMultimeter` carpet rule now controls integration with the new Redstone Multimeter mod.
- Any expensive calculations are behind a carpet rule check to make sure performance impact with the rule disabled is negligible. 
- Most RSMM related packets are ignored when the rule is disabled, apart from those needed to handle connections with RSMM clients.

2022-03-21 22:18 UTC, Earthcomputer requested changes
I am going to assume that code under the redstone.multimeter package is sound and doesn't need a strict review, so this is a review specifically on its integration with carpetmod.

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/command/ServerCommandManager.java.patch
> ++        func_71560_a(new MeterGroupCommand(this.field_184880_a)); // RSMM
This needs to go in the CarpetCommands file, it helps keep the patches clean.

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/tileentity/TileEntityChest.java.patch
> ++    private void onInvOpenOrClosed(boolean open) {
Additional methods like this should be in carpet code rather than in patch files, to keep the patches clean

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/tileentity/TileEntityChest.java.patch
> ++    private boolean isTrapped() {
I'm probably blind, but I don't see where this method is used.

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/world/World.java.patch
> ++    protected void onBlockUpdate(BlockPos pos, IBlockState state) {
Could these added methods be moved to TickTaskExecutor? Remember that in 1.12 carpet, the only implementation of World is WorldServer.

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/world/WorldServer.java.patch
> ++    public MultimeterServer getMultimeterServer() {
Again, I have a feeling that stuff like this should be moved into carpet code and out of patch files.

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/world/WorldServer.java.patch
> ++        endTickTask(); // RSMM
I'm a little bit worried that these endTickTask calls are vulnerable to update suppression, in that if update suppression happens, endTickTask won't be called. Maybe doesn't apply here but in other places. Could you have a quick scan over usages of endTickTask and perhaps its implementation with update suppression in mind to make sure this is not going to be a problem?

2022-03-21 22:18 UTC, Earthcomputer commented on patches/net/minecraft/world/WorldServer.java.patch
> ++    private int currentDepth; // RSMM
Is this only for block events? Maybe a more specific name then like `currentBlockEventDelay`

2022-03-22 00:37 UTC, SpaceWalkerRS commented on patches/net/minecraft/world/WorldServer.java.patch
> ++        endTickTask(); // RSMM
Everything else has been addressed, and this is not a real issue. That is to say, there is no danger of crashes/errors when a call to `endTickTask` is missed. The worst that can happen is that the tick phases reported by RSMM are a bit off for the rest of the tick.

2022-03-22 15:00 UTC, Earthcomputer reviewed
Looking much better now

2022-03-22 15:00 UTC, Earthcomputer commented on carpetmodSrc/carpet/CarpetServer.java
> +        rsmmChannel = new ToggleableChannelHandler(pluginChannels, legacyRsmmServer.createChannelHandler(), false);
This should probably be renamed to legacyRsmmChannel to avoid confusion

2022-03-22 15:37 UTC, Earthcomputer approved these changes

2022-03-22 18:28 UTC, merged