Debugchunk
gnembon/carpetmod112 pull request #56
Opened 2018-10-25 08:15 UTC by X-com

Best tool ever

2018-10-25 10:01 UTC, Earthcomputer requested changes
Cool. Just a few minor things to address then we can merge this

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/block/Block.java.patch
> ++    public String field_149770_b;
Should add a comment here mentioning that carpetmod made this public

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/block/BlockGrass.java.patch
> ++
this patch file can be removed altogether

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/entity/ai/EntityAIFollowOwner.java.patch
> ++    protected final EntityTameable field_75338_d;
Should add comment here saying that carpetmod changed access

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/server/MinecraftServer.java.patch
> ++
?

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/server/MinecraftServer.java.patch
> -+
Whitespace again

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/server/management/PlayerChunkMap.java.patch
> ++    	return new AbstractIterator<ChunkPos>() {
Perhaps this could be simplified to Iterators.transform?

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/tileentity/TileEntityHopper.java.patch
> ++        String prevReason = CarpetClientChunkLogger.reason;
This should use setReason and resetReason

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/tileentity/TileEntityHopper.java.patch
> ++        String prevReason = CarpetClientChunkLogger.reason;
Again here

2018-10-25 10:01 UTC, Earthcomputer commented on patches/net/minecraft/world/IBlockAccess.java.patch
> ++        String prevReason = CarpetClientChunkLogger.reason;
This can use setReason and resetReason

2018-10-25 10:09 UTC, Earthcomputer commented
Another thing I'm slightly worried about is the number of patch files that have been added. The more patch files we have, the higher the chance we change vanilla behaviour be leaking MCP bugs into the release of carpet. But the classes are at least small, and carpet has already changed pretty much every major class there is.

2018-10-25 12:32 UTC, gnembon commented on jsons/1.12.json
> +{"assetIndex": {"id": "1.12", "sha1": "1584b57c1a0b5e593fad1f5b8f78536ca640547b", "size": 143138, "totalSize": 129336389, "url": "https://launchermeta.mojang.com/v1/packages/1584b57c1a0b5e593fad1f5b8
I think this should be rather in .gitignore and removed from the repo

2018-10-25 12:41 UTC, Earthcomputer commented on jsons/1.12.json
> +{"assetIndex": {"id": "1.12", "sha1": "1584b57c1a0b5e593fad1f5b8f78536ca640547b", "size": 143138, "totalSize": 129336389, "url": "https://launchermeta.mojang.com/v1/packages/1584b57c1a0b5e593fad1f5b8
It's required for the buildsystem, I don't know why it was pretty printed to start with, but shouldn't change from this point on.

2018-10-26 17:32 UTC, gnembon requested changes

2018-10-26 17:32 UTC, gnembon commented on patches/net/minecraft/block/BlockPistonBase.java.patch
> ++            carpet.carpetclient.CarpetClientChunkLogger.setReason("Piston scheduled by power source");
aren't you supposed to reset the reason after stuff gets done?

2018-10-26 17:32 UTC, gnembon commented on patches/net/minecraft/entity/ai/EntityAITasks.java.patch
> ++                    carpet.carpetclient.CarpetClientChunkLogger.setReason("Entity" + entityaitasks$entityaitaskentry.field_75733_a.getTask());
I don't like the idea of adding getTask to every single AI task and modify 50 classes just to get the name of the task. Why don't you make the detault return 'other task' and attach class name (could be obfuscated) and on a few problematic tasks implement getTask so it is more verbose. I think the benefits of having all the tasks listed by their proper name outweight the patch mess it creates. Espeially that this new tool whatever you think about it - serves only a particular use case, works only with dedicated clients, but affect partally everybody that uses the carpet in general. I think for most tasks "task: "+this.getClass().toString() or something like that (don't know the call from the top of my head) would be sufficient. 
For instance for carpet profiler, I only added names to a few problematic tile and entites, leaving rest as 'some other entitiy" - for a vald reason not to have too much patches.

2018-10-26 17:36 UTC, Earthcomputer commented on patches/net/minecraft/entity/ai/EntityAITasks.java.patch
> ++                    carpet.carpetclient.CarpetClientChunkLogger.setReason("Entity" + entityaitasks$entityaitaskentry.field_75733_a.getTask());
Regarding the obfuscation, this could be worked around with the StackTraceDeobfuscator class also added by this PR.

2018-10-26 17:39 UTC, gnembon commented
I made my review a few days ago, just forgot to close it. Got the same impressoin. Its a tool with limited usecases that requires specitif clients (doesn't do anything on its own) and affects / creates large number of new patches. Technically that could be a mod on its own especially that is uses its own GUI.

2018-10-26 17:40 UTC, Earthcomputer commented
Well, actually, it has quite a fair amount of usecases. It's been invaluable to us already even before we released it for debugging various contraptions.

2019-02-17 06:28 UTC, merged