Implemented log changes
gnembon/carpetmod112 pull request #86
Opened 2019-05-02 20:27 UTC by Salandora

Based on issue #53 I implemented the changes.
I would like to get some feedback on this and maybe some improvement suggestions.

A bit of explaination:
Implemented persistent log options per-player as well as a server default configuration possability.

Server owners can either use the "/log defaults" command which provides an interactive menu or use the "/log setDefault" and "/log removeDefault" synatx to toggle the default subscriptions.

Players on the otherhand will be subscribed to the default subscriptions until they change their logging options, this way it's possible to have no log subscriptions at all.

Players can get back to the default subscriptions by using "/log reset", server owners can also force a "/log reset" on a player.
The clear option got renamed to reset as now it would have been misunderstandable. 

Subscriptions are now persistent and stored in a JSON file inside the world folder.

2019-05-08 23:31 UTC, Earthcomputer requested changes
Looks okay except for this one thing

2019-05-08 23:31 UTC, Earthcomputer commented on carpetmodSrc/carpet/logging/Logger.java
> +    private Map<String, String> subscribedPlayers;
Wasn't there a reason for the differentiation between online and offline players? That is, if there are no online subscribed players, the logger isn't run at all, saving on server performance.

2019-05-09 09:14 UTC, Salandora commented on carpetmodSrc/carpet/logging/Logger.java
> +    private Map<String, String> subscribedPlayers;
Thats still the case through the LoggerRegistry onPlayerConntected l/onPlayerDisconnected functions it is using the addPlayer and removePlayer functions now.

So there should be no overhead on the server if no player is subscribed to the logger.

2019-05-18 21:42 UTC, Earthcomputer commented on carpetmodSrc/carpet/logging/Logger.java
> +    private Map<String, String> subscribedPlayers;
Looks good then I guess.

2019-05-18 21:42 UTC, Earthcomputer approved these changes

2019-05-18 21:42 UTC, merged