A much better portal optimization
gnembon/carpetmod112 pull request #94
Opened 2019-11-24 01:56 UTC by LucunJi

2019-11-26 20:53 UTC, Earthcomputer requested changes
I haven't looked at the code thoroughly, as it's really up to Xcom, but in its current state it is unlikely to be merged, if at all. See my review.

2019-11-26 20:53 UTC, Earthcomputer commented on patches/net/minecraft/world/Teleporter.java.patch
> +-                }
A lot of vanilla code is removed here. In carpetmod you must be absolutely sure you are not changing vanilla behaviour. Don't run or not run any custom code without checking a rule first. It would be better to just use the vanilla code if the rule is set to `vanilla`, and use your AbstractPortalSearchers otherwise.

2019-11-27 19:08 UTC, X-com commented on patches/net/minecraft/world/Teleporter.java.patch
> +-                }
The code looks good but as Earthcomputer points out. Vanilla code is critical to maintain when the carpet rules are not active. Could you please help edit this section of the code to make it minimally invasive when the carpet rules are not in effect.

Two ways to go about it. One is to eject out of the method when any non-vanilla rule is enabled at the needed location. The other option is to simply add as few lines of code as possible in here to change the behavior. But given it looks like a large section of code change is needed then I would strongly suggest to go with the former option.

2019-11-29 05:14 UTC, LucunJi commented on patches/net/minecraft/world/Teleporter.java.patch
> +-                }
I restored the deleted vallina code. If the option is disabled, only vanilla searching code will be used. Also fixed a bug which causes chunks cached for optimization unable to be loaded, while they should be loaded for searching blocks in vanilla code.

2020-10-23 12:17 UTC, Earthcomputer approved these changes

2023-01-31 00:25 UTC, closed without merging